# Generated by Django 6.1.1 on 2026-09-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('cuisine_type', models.CharField(choices=[('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Fast Food', 'Fast Food'), ('Multi Cuisine', 'Multi Cuisine')], default='Multi Cuisine', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('delivery_time', models.PositiveIntegerField(default=30, help_text='Delivery time in minutes')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('is_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Starters', 'Starters'), ('Main Course', 'Main Course'), ('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Rice', 'Rice'), ('Pasta', 'Pasta'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('preparation_time', models.PositiveIntegerField(default=20, help_text='Preparation time in minutes')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='restaurants.restaurant')),
            ],
        ),
    ]
